"""
Reflective journaling companion for the Wellbeing page.

Scope, on purpose: this is NOT a therapist, NOT a diagnostic tool, and
never claims to be either. It does one thing -- reflect back what a
student wrote in a warm, non-judgmental way and gently encourage them to
keep going or talk to a real person -- and it does that one thing inside
a hard boundary: if wellbeing_store.scan_for_risk flags the entry, the
LLM is skipped entirely and a fixed, reviewed safety response is used
instead. That's deliberate, not a shortcut: a small local model
(llama3.2:1b) is not something to trust with the wording of a response to
someone in crisis, so the highest-stakes message in this whole module is
the one line of code that ISN'T generated by an LLM.
"""

from . import config
from . import llm_client
from . import wellbeing_store

SYSTEM_PROMPT = """You are a supportive reflective-journaling companion inside an
education app used in a correctional/rehabilitation education setting. A student
just wrote a private journal entry. Respond with 2-4 short sentences that:

- Acknowledge what they wrote in your own words (don't repeat it verbatim).
- Validate the feeling without judging it.
- Ask at most one gentle, open-ended question OR suggest one small next step
  (like a coping exercise on this page), not both.

Hard rules:
- You are NOT a therapist or doctor. Never diagnose, never name a mental-health
  condition, never suggest medication.
- Never give clinical or medical advice.
- Keep it short -- this is a reflection, not a lecture.
- Do not be falsely cheerful. Sit with difficult feelings instead of rushing
  to fix them.
- Write in plain, warm, everyday language."""

CHAT_SYSTEM_PROMPT = """You are a supportive companion chatbot inside an education
app used in a correctional/rehabilitation education setting. A student is having
an ongoing, casual conversation with you because they want someone to talk to.

Hard rules -- identical in spirit to the journaling reflection on this page:
- You are NOT a therapist, counselor, or doctor. Never diagnose, never name a
  mental-health condition, never suggest medication or treatment.
- Never give clinical or medical advice.
- Keep replies short: 2-4 sentences, conversational, not a lecture.
- Do not be falsely cheerful. Sit with difficult feelings instead of rushing
  to fix them.
- Ask at most one gentle, open-ended question per reply, OR suggest one small
  next step (like the breathing exercise or coping exercises on this page),
  not both.
- Write like a caring, grounded peer -- plain everyday language, not a script.
- If the student describes something that really needs a real person (a
  serious conflict, a health issue, anything urgent), gently encourage them
  to talk to facility staff or a counselor rather than trying to solve it
  yourself."""

# How many prior chat turns (not pairs) get sent back to the model as
# context. Small local models don't need or reliably use a long history,
# and every extra turn costs latency -- keep this modest.
MAX_CHAT_HISTORY_TURNS = 8


def _safety_first_reply() -> str:
    res = wellbeing_store.crisis_resources()
    return (
        "Thank you for writing this down -- that took courage. What you're "
        "describing sounds really heavy, and I want to make sure you're not "
        f"carrying it alone. Please reach out to {config.CRISIS_CONTACT} right "
        "now and talk to someone in person. This page has been flagged for a "
        "staff follow-up as well, but please don't wait for that -- talk to "
        "someone today."
    )


def reflect(student_id: str, text: str) -> dict:
    """Returns {"reflection": str, "flagged": bool, "flag_reason": str|None}.
    Persists the entry via wellbeing_store before returning."""
    risk_match = wellbeing_store.scan_for_risk(text)

    if risk_match:
        reflection = _safety_first_reply()
        entry = wellbeing_store.add_journal_entry(student_id, text, reflection, flag_reason=risk_match)
        return {
            "reflection": reflection,
            "flagged": True,
            "resources": wellbeing_store.crisis_resources(),
            "entry_id": entry["id"],
        }

    try:
        reflection = llm_client.call_llm(SYSTEM_PROMPT, text)
    except RuntimeError:
        # Ollama down / model not pulled -- degrade to a plain, honest
        # acknowledgement rather than failing the whole request. Journaling
        # should still work (and still be saved) even without the LLM up.
        reflection = (
            "Thanks for writing this down. I couldn't reach the reflection "
            "model just now, but your entry has been saved."
        )

    entry = wellbeing_store.add_journal_entry(student_id, text, reflection, flag_reason=None)
    return {
        "reflection": reflection,
        "flagged": False,
        "resources": None,
        "entry_id": entry["id"],
    }


def chat(student_id: str, text: str) -> dict:
    """One turn of the companion chatbot. Returns {"reply": str, "flagged":
    bool, "resources": dict|None, "entry_id": str}. Persists both the
    student's message and the reply via wellbeing_store before returning --
    same safety-first bypass as reflect(): a risk match skips the LLM
    entirely."""
    risk_match = wellbeing_store.scan_for_risk(text)
    prior_history = wellbeing_store.list_chat(student_id)  # before this turn
    wellbeing_store.add_chat_message(student_id, "user", text, flag_reason=risk_match)

    if risk_match:
        reply = _safety_first_reply()
        assistant_entry = wellbeing_store.add_chat_message(student_id, "assistant", reply)
        return {
            "reply": reply,
            "flagged": True,
            "resources": wellbeing_store.crisis_resources(),
            "entry_id": assistant_entry["id"],
        }

    recent = prior_history[-MAX_CHAT_HISTORY_TURNS:]
    messages = [{"role": "system", "content": CHAT_SYSTEM_PROMPT}]
    for turn in recent:
        role = "assistant" if turn["role"] == "assistant" else "user"
        messages.append({"role": role, "content": turn["text"]})
    messages.append({"role": "user", "content": text})

    try:
        reply = llm_client.call_llm_messages(messages)
    except RuntimeError:
        # Same degrade-gracefully approach as reflect(): the chat log still
        # works even if Ollama is down, it just says so.
        reply = (
            "Thanks for sharing that. I couldn't reach the chat model just "
            "now -- mind trying again in a moment?"
        )

    assistant_entry = wellbeing_store.add_chat_message(student_id, "assistant", reply)
    return {
        "reply": reply,
        "flagged": False,
        "resources": None,
        "entry_id": assistant_entry["id"],
    }
